### ISSUE TITLE
it is showing a value error

### ISSUE THREAD

**Issue by parthgoe1** [apoorva-dave/LicensePlateDetector#1]
min_row, min_col, max_row, max_col = region.bbox

ValueError: too many values to unpack (expected 4)

**Comment by apoorva-dave** [comment]
can you please elaborate what all changes you did? what was the input file? And you are getting this error in DetectPlate.py?

**Comment by parthgoe1** [comment]
I did not make any changes to the code. DetectPlate.py is working perfectly. But when I import it to segmentcharacter.py it makes a 3d array and gives an error.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jimy2020** [comment]
In the 
min_row, min_col, max_row, max_col = region.bbox Line i am getting following error in DetectPlate.py?
ValueError: too many values to unpack (expected 4)

**Comment by apoorva-dave** [comment]
Are you using some other image or video as I am unable to reproduce it. My friends have also used the same code and with the image/video examples given in repo, it is working fine for them. Can you share the image which you are using to test it?

On printing region.bbox what are you getting?  It should be sequence of values like (718, 1115, 730, 1129)

**Comment by jimy2020** [comment]
Hi dear apoorva
I use image/video examples given in repo. But run python 3.6. When
print(region) i see in IPython console following output
<skimage.measure._regionprops._RegionProperties object at
0x000002E043AB6208>

**Comment by jimy2020** [comment]
Also print(region.bbox) in the console see follow out put
(0,489,0,63,532,3)
I uesd video12.mp4.

**Comment by apoorva-dave** [comment]
I tried looking into it but still couldn't identify why region.bbox is giving you 6 values rather than 4.
Did you try capturing these values and see if you are getting the same result?
eg : take any 2 dummy variables
t1, min_row, t2, min_col, max_row,

**Comment by jimy2020** [comment]
I fixed this error using 2 dummy variables as following
min_row, min_col,null, max_row, max_col,null= region.bbox
But I went through the following error in DetectPlate.py.
ValueError: 3-dimensional arrays must be of dtype unsigned byte,
unsigned short, float32 or float64؟

**Comment by G-Slient** [comment]
I am getting the same error. could you fix this error?

**Comment by sandan000** [comment]
> I am getting the same error. could you fix this error?

I got the same error too. You can try to change image from RGB to gray format.
