### ISSUE TITLE
The output is not correct

### ISSUE THREAD

**Issue by Naimur017** [apoorva-dave/LicensePlateDetector#11]
@apoorva-dave 
the car number is not given acquired in console. see the frist picture .Whats wrong actually.
![2019-07-23 (1)](https://user-images.githubusercontent.com/27545384/61711960-15cd4b80-ad77-11e9-953f-d91e789f6795.png)
![2019-07-23](https://user-images.githubusercontent.com/27545384/61711961-1665e200-ad77-11e9-98a1-9ba28b2ee472.png)

**Comment by apoorva-dave** [comment]
This issue occurs when CCA is not done properly on the image. I think you are trying on the test video. Try capturing frames differently by stopping the video at different times.
As mentioned the code is not robust for license plate detection in videos.
