### ISSUE TITLE
Not getting predicted characters same as segmented characters

### ISSUE THREAD

**Issue by Shubham191297** [apoorva-dave/LicensePlateDetector#12]
When I run predict characters file it does not predict correct characters. And i dont know how the model works so how to resolve that

**Comment by apoorva-dave** [comment]
The model might not necessarily predict correct characters all the time for each image.
TrainRecognizeCharacters.py is the file where I am training an SVC model to predict characters. The code here is pretty simple.
You can try improving the accuracy by creating any other model of your choice. You can refer to Scikit Learn documentation to know how you can train your own model.
