### ISSUE TITLE
Output not correct

### ISSUE THREAD

**Issue by Abdullah211w** [apoorva-dave/LicensePlateDetector#14]
Hi there
I am a student of bachelors and i am making a project related to your work, i am looking for a code in which an image of a video of a car is given as an input and it in return it gives is number plate,
i came across your code and it was really good but the problem is that it is not extracting right number on the number plate, if i give it more images in training data will it become correct then?
or if you can suggest me something, i will be very glade
And also if you know some other codes or work related to my project, you can suggest me i will really glad
Thank you so much
Looking forword to your reponse

**Comment by littleGiao** [comment]
Hi I am in the same situation with you. Do you solve the problem?

**Comment by Abdullah211w** [comment]
No i haven't found any solution,
If you do please let me know too

> Hi I am in the same situation with you. Do you solve the problem?

**Comment by abusufyansher1** [comment]
Do you find any solution,,, ? prediction is not correct

**Comment by qamar-abbas803** [comment]
Prediction of Alphabets is not correct.....!!!!

**Comment by apoorva-dave** [comment]
The model is not having 100% accuracy. So some alphabets can be predicted wrong as well.  You can try training it with more data. It handles cases only when there is 1 car image and not multiple objects in the same frame.
