### ISSUE TITLE
Trying to unpickle estimator SVC

### ISSUE THREAD

**Issue by Amrrx** [apoorva-dave/LicensePlateDetector#16]
`UserWarning: Trying to unpickle estimator SVC from version 0.19.1 when using version 0.19.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
`
I wonder if you can provide us with more information or support us with Scikit-learn v0.19.1 as i can assume it causes that proplem

**Comment by apoorva-dave** [comment]
Yes fixed this issue.  There is a problem when we use different versions of scikit-learn the one on which model is trained and the one that you are using. So I have added requirements.txt to avoid this issue. And also updated trained model accordingly. You can install all the dependencies using pip install -r requirements.txt
