### ISSUE TITLE
FileNotFoundError - cannot find ./output/frame106.jpg

### ISSUE THREAD

**Issue by shreyanshtiwari28** [apoorva-dave/LicensePlateDetector#18]
I cloned the repository and tried to run the project with Pycharm IDE. But its throwing a FileNotFoundError: No such file: '...\LicensePlateDetector\output\frame106.jpg'
please help, I'm a beginner with python and ML

**Comment by moxgeek** [comment]
you need to create the output directory in your project folder.

**Comment by apoorva-dave** [comment]
Fixed the issue to automatically create output folder. Thanks for pointing it!
