### ISSUE TITLE
how to work on image..... it only take videos

### ISSUE THREAD

**Issue by whodanyalahmed** [apoorva-dave/LicensePlateDetector#22]
`filename = './car.png'`
when I change this to image it shows this error:

> FileNotFoundError: No such file: 'I:\clients\NumperPlateExtractor\output\frame-1.jpg'

**Comment by apoorva-dave** [comment]
If you want to work with images, you can comment out the part where we are taking videos as input and then detecting plate. And uncomment below line -
 car_image = imread("car.png", as_gray=True)
Also, if you want you can raise a PR to provide user an option whether to upload car or videos.
