### ISSUE TITLE
testing accuracy is low

### ISSUE THREAD

**Issue by Cgraj07** [apoorva-dave/LicensePlateDetector#34]
I use same image and and mode that you posted in git but for me it predict bad for example(7 as Z 3 as 8 and S as 8) so please use more data to training and reupload the model it will be better for beginner like me
otherwise the everything is fine model as well as segment extraction is good

**Comment by apoorva-dave** [comment]
I have been very much occupied with my work and did not get a chance to check this. I hope you were able to train a model for yourself. If not, I will try if I can put a better model.
