### ISSUE TITLE
How do I use different input?

### ISSUE THREAD

**Issue by leanjiji** [apoorva-dave/LicensePlateDetector#4]
I'm sorry, but I am not very familiar with digital image processing.
Could you explain to me further how can I use different input, eg, my own video?
It didn't detect the car plate properly, sometimes it gave me index out of range, I am guessing this is because it completely did not detect something at all in the video.
Is it because I have to train the program to detect the font of my car plate in my video?
If so, how can I do that?

Sorry and thank you, would really appreciate your help because this is very important to me.

**Comment by apoorva-dave** [comment]
Hi, sorry for late response. 

In this project, license plates can be detected from videos with a single car and not multiple. Also it is using CCA to detect plate, which finds connected regions in the video and if not found gives vague result.
You can check the article https://towardsdatascience.com/number-plate-detection-with-supervisely-and-tensorflow-part-1-e84c74d4382c which uses tensorflow to detect license plates. This might be helpful.
