### ISSUE TITLE
Multiple Vehicles

### ISSUE THREAD

**Issue by mnabeel786** [apoorva-dave/LicensePlateDetector#6]
Hi, When i am giving input of multiple cars(through a video)but it is generating only one frame of any random car. it should shows every car. How can i detect multiple cars in the video..

**Comment by apoorva-dave** [comment]
The code is implemented only for 1 car in a video. You will have to check for this as to how you can implement CCA for such scenarios.

**Comment by mnabeel786** [comment]
Hi Apoorva wanted ask you one thing, that i want to take the number plate as an string and to store in my database, but the thing it is working on the image but not on the video..
here is my code can you please tell me where i am doing wrong. it is giving me an error Element 0 value is unsupported.
connection = cx_Oracle.connect('nabeel/1234@localhost/xe')
cursor = connection.cursor()
dtime=datetime.datetime.now()
cursor.execute("insert into number_plate(reg_no,tstamp) values(:licPlate,:ts)",licPlate=characters)
cursor.setinputsizes(ts=cx_Oracle.TIMESTAMP)
cursor.execute(None, {'ts':dtime})
connection.commit()
connection.close()
