### ISSUE TITLE
Where are the cv2 file?

### ISSUE THREAD

**Issue by saulocastillos** [apoorva-dave/LicensePlateDetector#8]
Hey Apoorva Dave

Where are the cv2 which is imported in DetectPlate.py?

**Comment by apoorva-dave** [comment]
By doing import cv2 we are importing open cv module in python. It has to be first installed using pip and then it can be used to read and process images. Please check this link to get more info [https://www.geeksforgeeks.org/reading-image-opencv-using-python/](url)

**Comment by saulocastillos** [comment]
Thank you
