### ISSUE TITLE
increase images in tarining module

### ISSUE THREAD

**Issue by akilaariyarathne** [apoorva-dave/LicensePlateDetector#9]
When training the data set if we increase the no of images give an error 
 raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: 'C:\sw\pyproject\LicensePlateDetector-master\train20X20\0\0_11.jpg'

**Comment by apoorva-dave** [comment]
The training set has 9 images of each character/digit. You ll have to add an image inside the specific folder and of the required size.
